version: "3.9"

services:
  backend:
    build: .
    container_name: blog-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal  # for running container in docker , local mysql use
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=blogdb
    depends_on:
      - db


  frontend:
    build: ./frontend
    container_name: blog-frontend
    ports:
      - "5173:5173" #  CRA use kar raha hai toh yaha 3000 hoga
    stdin_open: true
    tty: true        # for interactive mode
    depends_on:
      - backend
